### ISSUE TITLE
[Global] Ensure text remains visible during webfont load

### ISSUE THREAD

**Issue by rofe** [davidnuescheler/theblog#106]
From https://web.dev/font-display/

The easiest way to avoid showing invisible text while custom fonts load is to temporarily show a system font. By including `font-display: swap` in your `@font-face` style, you can avoid flashing of invisible text (FOIT) in most modern browsers:

```css
@font-face {
  font-family: 'Pacifico';
  font-style: normal;
  font-weight: 400;
  src: local('Pacifico Regular'), local('Pacifico-Regular'), url(https://fonts.gstatic.com/s/pacifico/v12/FwZY7-Qmy14u9lezJ-6H6MmBp0u-.woff2) format('woff2');
  font-display: swap;
}
```
